#pragma once

#define BOARD_SIZE 10
#define BATTLE_SHIP_HP 4
#define BATTLE_SHIP_SIZE 4
#define BATTLE_SHIP_RENDER_LETTER 'B'
#define BATTLE_SHIP_DISPLAY_NAME "Battleship"
#define CARRIER_SHIP_HP 5
#define CARRIER_SHIP_SIZE 5
#define CARRIER_SHIP_RENDER_LETTER 'C'
#define CARRIER_SHIP_DISPLAY_NAME "Carrier"
#define CRUISER_SHIP_HP 3
#define CRUISER_SHIP_SIZE 3
#define CRUISER_SHIP_RENDER_LETTER 'R'
#define CRUISER_SHIP_DISPLAY_NAME "Cruiser"
#define DESTROYER_SHIP_HP 2
#define DESTROYER_SHIP_SIZE 2
#define DESTROYER_SHIP_RENDER_LETTER 'D'
#define DESTROYER_SHIP_DISPLAY_NAME "Destroyer"
#define SUBMARINE_SHIP_HP 3
#define SUBMARINE_SHIP_SIZE 3
#define SUBMARINE_SHIP_RENDER_LETTER 'S'
#define SUBMARINE_SHIP_DISPLAY_NAME "Submarine"
#define REVEALED_SHIP_POSITION_CHAR 'O'

#define FREE_CELL_CHAR '.'
#define MISSED_CELL_CHAR '~'
#define HIT_CELL_CHAR 'X'
#define CELL_SEPARATOR_CHAR ' '
#define FIELD_SEPARATOR_STRING "-------------------"
#define PROMPT "< "